title: "Blog"
email: avagyanmonika3@gmail.com
timezone: UTC +4
baseurl: "/monica-blog.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Monica
paginate: 30
disqus: 'demowebsite'
locale: hy
lang: hy
feed_items: 10
feed_update_period: weekly
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  monica:
    name: Monica
    display_name: Monica
    avatar: 'assets/images/logo.png'
    email: avagyanmonika3@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    linkedin: https://www.linkedin.com/in/monica-avagyan/
    description: "In this series of articles, we will explore the latest trends, breakthroughs, and notable developments in IT, AI, and the digital sphere within all world. "
  
# Social
social:
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
